stages:
  - build
  - test

build-job: # This job runs in the build stage, which runs first.
  stage: build
  # Symfony and docker-compose commands to build the app
  script:
      - docker-compose up -d --build
      - docker-compose exec php-fpm composer install
      - docker-compose exec php-fpm php bin/console doctrine:database:create
      - docker-compose exec php-fpm php bin/console doctrine:migrations:migrate
      - docker-compose exec php-fpm php bin/console doctrine:fixtures:load
      - docker-compose exec php-fpm php bin/console cache:clear
      - docker-compose exec php-fpm php bin/console cache:clear --env=test
  tags:
    - build


unit-test-job:   # This job runs in the test stage.
  stage: test
  # Symfony and docker-compose commands to run the tests
  script:
    - docker-compose exec php-fpm php bin/console doctrine:database:create --env=test
    - docker-compose exec php-fpm php bin/console doctrine:migrations:migrate --env=test
    - docker-compose exec php-fpm php bin/console doctrine:fixtures:load --env=test
    - docker-compose exec php-fpm php bin/phpunit
  tags:
    - test


