version: '3.8' # Utilisez la version appropriée de Docker Compose

services:
  nginx:
    image: nginx:latest
    container_name: ucreate_nginx
    ports:
      - "8080:8080" # Port de l'hôte : Port du conteneur
    volumes:
      - ./ucreate/nginx.conf:/etc/nginx/nginx.conf:ro # Montage du fichier nginx.conf
      - ./ucreate:/var/www/symfony:ro # Montage du projet Symfony en lecture seule
    depends_on:
      - php-fpm
    networks:
      - ucreate_network
  
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./ucreate:/var/www/symfony:rw # Montage du projet Symfony en lecture/écriture
    ports:
      - "9000:9000" # Port de l'hôte : Port du conteneur
    networks:
      - ucreate_network
    command: sh -c "composer install --ignore-platform-reqs && php-fpm"

networks:
  ucreate_network:
