version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: ucreate_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www/symfony:ro
    depends_on:
      - php-fpm
      - db
    networks:
      - ucreate_network


  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    networks:
      - ucreate_network

  db:
    image: mysql:latest
    container_name: ucreate_db
    environment:
      MYSQL_ROOT_PASSWORD: kali
      MYSQL_DATABASE: ucreate
      MYSQL_USER: kali
      MYSQL_PASSWORD: kali
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ucreate_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ucreate_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: kali
    ports:
      - "8081:80"
    networks:
      - ucreate_network

volumes:
  db_data:

networks:
  ucreate_network:
