version: '3.8' # Utilisez la version appropriée de Docker Compose

services:
  nginx:
    image: nginx:latest
    container_name: ucreate_nginx
    ports:
      - "8080:8080" # Port de l'hôte : Port du conteneur
    volumes:
      - ./ucreate/nginx.conf:/etc/nginx/nginx.conf:ro # Montage du fichier nginx.conf
      - ./ucreate:/var/www/symfony:ro # Montage de votre projet Symfony en lecture seule
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.1-fpm # Utilisez l'image PHP appropriée
    container_name: ucreate_php
    volumes:
      - ./ucreate:/var/www/symfony:rw # Montage de votre projet Symfony en lecture/écriture

# Vous pouvez également ajouter d'autres services comme une base de données (MySQL, PostgreSQL, etc.) si nécessaire.
